// ---------------- Users ---------------- //

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users?offset=0&limit=2&order=newest
###
GET http://localhost:3000/users/ac240971-6f59-40f5-b9ac-3f343e46e80c

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "hellowwwww@email.com",
  "firstName": "Chale",
  "lastName": "Smith",
  "address": "UK"
}

###
PATCH http://localhost:3000/users/51946044-7baa-4e9a-a1fd-f9bb522db894
Content-Type: application/json

{
  "email": "kelwv113455@email.com",
  "firstName": "James",
  "lastName": "Jhon",
  "address": "광주광역시"
}

###
DELETE http://localhost:3000/users/14624c5e-0c8d-445c-9e6a-3b9f594c2efc



// ---------------- Products ---------------- //

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products?order=priceHighest&category=BEAUTY

###
GET http://localhost:3000/products/d7a30079-81bf-4432-81d9-bf156b234162

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "치마",        
  "description": "연청치마",
  "category": "FASHION",
  "price": 3500,
  "stock": 3 
}

###
PATCH  http://localhost:3000/products/194c9121-370e-4351-bc53-1620cd7fcbda
Content-Type: application/json

{
  "name": "화장품",        
  "description": "선크림",
  "category": "BEAUTY",
  "price": 10009,
  "stock": 6
}

###
DELETE   http://localhost:3000/products/f5b9f2ab-9d6e-41a8-8ca4-fa999c79cfde